[tool.poetry]
name = "airflow-mlflow"
version = "0.1.0"
description = ""
authors = ["antenoraires <antenoraires37@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
mlflow = "^2.20.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
